components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      in: header
  responses:
    Success:
      description: object
      content:
        application/json:
          schema:
            type: object
    Unauthorized:
      description: You do not have permission to access this
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 403
              message:
                type: string
                example: Unauthorized
    InternalError:
      description: Unable to process the request
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 500
              message:
                type: string
                example: Internal Server Error
