#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# declare HAS_CHANGE=$(git show --name-only -r --stat --oneline HEAD^^..HEAD | grep 'src')

# if [ -n "$HAS_SHARED_CHANGE" ] && [ -z "$HAS_CHANGE" ]; then
#   echo "Shared changed"
#   yarn docker && yarn tsc --build && yarn test tests/db/** 
# fi

# if [ -n "$HAS_CHANGE" ]; then
#   echo "Server or shared changed, running server tests"
#   yarn docker && yarn tsc --build && yarn test
# fi

yarn docker && yarn tsc --build && yarn test
