name: Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn
      - run: docker compose up --wait
      - run: yarn build
      - run: yarn test
